'use strict';
const el=id=>document.getElementById(id);let token='',page=1;
const pretty=value=>JSON.stringify(value,null,2);
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
async function api(path,options={}){const headers={'Accept':'application/json',...(options.headers||{})};if(options.method==='POST'){headers['Content-Type']='application/json';headers['X-Project-Health-Token']=token;}const response=await fetch('/api/knowledge/'+path,{...options,headers});const payload=await response.json();if(!response.ok||payload.status==='error')throw new Error(payload.error||response.statusText);return payload;}
function message(text){el('message').textContent=text||'';}
async function run(fn){try{message('');await fn();}catch(error){message(error.message||String(error));}}
function renderEntries(id,items,onOpen){const host=el(id);host.innerHTML='';if(!items||!items.length){host.innerHTML='<p class="empty">No matches.</p>';return;}for(const item of items){const div=document.createElement('div');div.className='entry';const label=item.path||item.title||('Task '+item.task_id);const button=document.createElement('button');button.type='button';button.textContent=label;button.onclick=()=>onOpen&&onOpen(item);div.appendChild(button);const small=document.createElement('small');small.textContent=item.evidence?item.evidence.join(' · '):('score '+(item.score??'n/a'));div.appendChild(small);host.appendChild(div);}}
async function loadStatus(){const state=await api('status');el('snapshot').textContent=state.revision?state.revision.slice(0,12):state.status;el('status').textContent=state.message||((state.fetch_error?'Fetch warning: '+state.fetch_error+'. ':'')+'revision '+(state.revision||'n/a'));const tasks=state.tasks||{};el('metrics').innerHTML='<span class="metric">sources '+esc(state.source_count??0)+'</span><span class="metric">tasks '+esc(tasks.total??0)+'</span><span class="metric">task data '+(tasks.initialized?'ready':'uninitialized')+'</span>';await loadTasks(1);}
async function loadConfig(){el('config-json').value=pretty(await api('config'));}
async function loadTasks(next){page=next;const data=await api('tasks?page='+page);const body=el('task-body');body.innerHTML='';el('task-empty').textContent=data.initialized?'': 'This template has no Taskmaster task data yet. Add real .taskmaster/tasks files, then scan again.';for(const item of data.items){const tr=document.createElement('tr');const id=document.createElement('td');const btn=document.createElement('button');btn.type='button';btn.textContent=String(item.id??'');btn.onclick=()=>openTask(item.id);id.appendChild(btn);const title=document.createElement('td');title.textContent=item.title||'';const status=document.createElement('td');status.textContent=item.status||'';const deps=document.createElement('td');deps.textContent=Array.isArray(item.dependencies)?item.dependencies.join(', '):String(item.dependencies||'');tr.append(id,title,status,deps);body.appendChild(tr);}const pager=el('pager');pager.innerHTML='';const prev=document.createElement('button');prev.type='button';prev.textContent='Previous';prev.disabled=data.page<=1;prev.onclick=()=>loadTasks(data.page-1);const info=document.createElement('span');info.textContent=`Page ${data.page} / ${data.pages} · ${data.total} tasks`;const nextBtn=document.createElement('button');nextBtn.type='button';nextBtn.textContent='Next';nextBtn.disabled=data.page>=data.pages;nextBtn.onclick=()=>loadTasks(data.page+1);pager.append(prev,info,nextBtn);}
async function openTask(id){const data=await api('task?id='+encodeURIComponent(id));el('detail-title').textContent='Task '+id;el('detail-body').textContent=pretty(data);el('detail').showModal();}
async function search(){const data=await api('query',{method:'POST',body:JSON.stringify({query:el('query').value,consumer:el('consumer').value})});el('results').hidden=false;el('queries').textContent='Executed queries: '+data.executed_queries.join(' | ');el('stale').hidden=!data.snapshot_stale;el('stale').textContent=data.snapshot_stale?'Snapshot revision differs from workspace HEAD. Treat this as exploration of the scanned revision.':'';renderEntries('tasks-action',data.actionable_results.tasks,item=>openTask(item.task_id));renderEntries('config-action',data.actionable_results.configuration,item=>setTarget(item.path));renderEntries('code-action',data.actionable_results.code,item=>setTarget(item.path));renderEntries('tests-action',data.actionable_results.tests,item=>setTarget(item.path));renderEntries('knowledge',data.knowledge,item=>setTarget(item.path));el('impact').textContent=pretty(data.impact_preview);}
function setTarget(path){el('query').value=path;run(search);}
el('scan').onclick=()=>run(async()=>{await api('scan',{method:'POST',body:JSON.stringify({fetch:true})});await loadStatus();});
el('reload-config').onclick=()=>run(loadConfig);
el('save-config').onclick=()=>run(async()=>{const payload=JSON.parse(el('config-json').value);await api('config',{method:'POST',body:JSON.stringify(payload)});message('Configuration saved. Scan again to apply source changes.');});
el('query-form').onsubmit=event=>{event.preventDefault();run(search);};
el('close-detail').onclick=()=>el('detail').close();
el('detail').addEventListener('click',event=>{if(event.target===el('detail'))el('detail').close();});
run(async()=>{token=(await api('session')).token;await Promise.all([loadStatus(),loadConfig()]);});
