name: Windows Export Slim

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  export:
    uses: ./.github/workflows/windows-release.yml
    with:
      artifact_name: windows-export-slim
      export_size_max_mb: '150'
